### ISSUE TITLE
Binary releases of Ctrl-Q 1.6 and above are built with a JDK 17 target, making them incompatible with 1.17.1 despite being marked as such.

### ISSUE THREAD

**Issue by akemin-dayo** [Mrredstone5230/Ctrl-Q#3]
Binary releases of Ctrl-Q 1.6 and above are built with a JDK 17 target, making them incompatible with 1.17.1 despite being marked as such.

The last binary release that works with 1.17.1 is 1.5.

```
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config ctrl-q.mixins.json for mod ctrl-q
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config ctrl-q.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 16.0, ASM 9.3 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more
```

**Comment by SB2DD** [comment]
It works if you put your game's jdk for 17. I'm able to do that on MultiMC and it works fine. Nonetheless, as changing jdk version isn't normal, I will see what I can do to also support older versions of the game. Thanks!

**Comment by SB2DD** [comment]
I just made releases for every fabric versions + 1.12 forge. Hope it helps! (1.17 is with jdk 16 now lol)
