### ISSUE TITLE
1.12.2 error with liteloader

### ISSUE THREAD

**Issue by ereac** [Mrredstone5230/Ctrl-Q#6]
[14:38:03] [main/WARN]: The coremod Ctrl-Q Forge (me.polishkrowa.ctrlqforge.core.CoreMod) is not signed!
[14:38:03] [main/WARN]: Mixin config ctrlq-forge.mixins.json requires mixin subsystem version 0.8 but 0.7.5 was found. The mixin config will not be applied.
Exception caught from launcher
org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config ctrlq-forge.mixins.json requires mixin subsystem version 0.8
	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:282)
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:56)
	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:103)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:146)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanClasspath(MixinPlatformManager.java:230)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:199)
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:189)
	at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:62)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Exception in thread "main" [14:38:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:38:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[14:38:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[14:38:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:102)
[14:38:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:987)
[14:38:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:75)

**Comment by SB2DD** [comment]
I'm very sorry, but Liteloader isn't currently officially supported.
